.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. layercoin_qt test_layercoin_qt
clean: FORCE
	$(MAKE) -C .. layercoin_qt_clean test_layercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_layercoin_qt_check
layercoin-qt layercoin-qt.exe: FORCE
	 $(MAKE) -C .. layercoin_qt
